#-------------------------------
# General Site Settings

title: Import Coffee
description: 
baseurl: "https://www.blog.importcoffee.es" # the subpath of your site, e.g. /blog
url: "https://www.blog.importcoffee.es" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Import Coffee
author-avatar: 09.jpg


#-------------------------------
# Contact links
facebook:  https://google.com/ # Add your Facebook handle
twitter:   https://twitter.com/ # Add your Facebook handle
instagram: https://www.instagram.com/import.coffee/ # Add your Facebook handle
pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-admin

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
